#spring.application.name=users-account-service
#server.servlet.session.cookie.name=user_session
#server.servlet.session.cookie.http-only=true
#server.servlet.session.cookie.secure=true
server:
  port: 8080


spring:
  application:
    name: users-account-service

  messages:
    encoding: UTF-8

  profiles:
    active: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-account-service
    username: postgres
    password: 1111

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        show_sql: true

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://tld18dev.au.auth0.com/
          audiences: https://userapi



#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org:
      springframework.jdbc: DEBUG
